/* Generated By:JavaCC: Do not edit this line. TiraTeimaParserTokenManager.java */
package tirateima.parser;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import java.util.Stack;
import tirateima.controlador.Controlador;
import tirateima.controlador.Command;
import tirateima.controlador.Operador;
import tirateima.controlador.CommandAttribution;
import tirateima.controlador.CommandJump;
import tirateima.controlador.CommandConditionalJump;
import tirateima.controlador.CommandNewType;
import tirateima.controlador.CommandNewVar;
import tirateima.controlador.CommandNewVarText;
import tirateima.controlador.CommandDirectPointer;
import tirateima.controlador.CommandReadInput;
import tirateima.controlador.FunctionDeclaration;
import tirateima.controlador.CommandStartFunction;
import tirateima.controlador.CommandEndFunction;
import tirateima.controlador.CommandOperationCall;
import tirateima.controlador.CommandInsertText;
import tirateima.controlador.Index;
import tirateima.controlador.Step;
import tirateima.controlador.Type;
import tirateima.controlador.TypeId;
import tirateima.controlador.VarDefinition;

/** Token Manager. */
public class TiraTeimaParserTokenManager implements TiraTeimaParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 9:
         jjmatchedKind = 2;
         return jjMoveNfa_0(0, 0);
      case 10:
         jjmatchedKind = 3;
         return jjMoveNfa_0(0, 0);
      case 12:
         jjmatchedKind = 5;
         return jjMoveNfa_0(0, 0);
      case 13:
         jjmatchedKind = 4;
         return jjMoveNfa_0(0, 0);
      case 32:
         jjmatchedKind = 1;
         return jjMoveNfa_0(0, 0);
      case 33:
         jjmatchedKind = 73;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10L);
      case 37:
         jjmatchedKind = 78;
         return jjMoveNfa_0(0, 0);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4L);
      case 40:
         jjmatchedKind = 58;
         return jjMoveNfa_0(0, 0);
      case 41:
         jjmatchedKind = 59;
         return jjMoveNfa_0(0, 0);
      case 42:
         jjmatchedKind = 76;
         return jjMoveNfa_0(0, 0);
      case 43:
         jjmatchedKind = 74;
         return jjMoveNfa_0(0, 0);
      case 44:
         jjmatchedKind = 61;
         return jjMoveNfa_0(0, 0);
      case 45:
         jjmatchedKind = 75;
         return jjMoveNfa_0(0, 0);
      case 46:
         jjmatchedKind = 60;
         return jjMoveNfa_0(0, 0);
      case 47:
         jjmatchedKind = 77;
         return jjMoveNfa_0(0, 0);
      case 58:
         jjmatchedKind = 62;
         return jjMoveNfa_0(0, 0);
      case 59:
         jjmatchedKind = 63;
         return jjMoveNfa_0(0, 0);
      case 60:
         jjmatchedKind = 69;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80L);
      case 61:
         jjmatchedKind = 64;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8L);
      case 62:
         jjmatchedKind = 70;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100L);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x4004000000L, 0x0L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x40000L, 0x0L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x118081010000L, 0x0L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x200400000000L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x1100000000L, 0x0L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x80000004000L, 0x0L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x1000L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x2000000000L, 0x0L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x40000080000L, 0x0L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x80007800a000L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x1000202020000L, 0x0L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x20800200000L, 0x0L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x400000100000L, 0x0L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0xc00000L, 0x0L);
      case 91:
         jjmatchedKind = 56;
         return jjMoveNfa_0(0, 0);
      case 93:
         jjmatchedKind = 57;
         return jjMoveNfa_0(0, 0);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x4004000000L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x40000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x118081010000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x200400000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x1100000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x80000004000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x1000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x2000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x40000080000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x80007800a000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x1000202020000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20800200000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x400000100000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0xc00000L, 0x0L);
      case 123:
         jjmatchedKind = 54;
         return jjMoveNfa_0(0, 0);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2L);
      case 125:
         jjmatchedKind = 55;
         return jjMoveNfa_0(0, 0);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 0);
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x4L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 1;
         }
         break;
      case 61:
         if ((active1 & 0x8L) != 0L)
         {
            jjmatchedKind = 67;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x10L) != 0L)
         {
            jjmatchedKind = 68;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x100L) != 0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 1;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x421000000000L, active1, 0L);
      case 69:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x80007820a000L, active1, 0L);
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x280400004000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x1580031c0000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x800c00000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x200020000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x2100000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x421000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x80007820a000L, active1, 0L);
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x280400004000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x1580031c0000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x800c00000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x200020000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x2100000000L, active1, 0L);
      case 124:
         if ((active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 1;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(0, 1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_0(0, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 1);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x260018000L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000002000L);
      case 68:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000d80000L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000000L);
      case 77:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x20001000000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x100100001000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x4080040000L);
      case 82:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10000020000L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0014000000L);
      case 84:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 2;
         }
         break;
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L);
      case 87:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 88:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x260018000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000002000L);
      case 100:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000d80000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x3000000000L);
      case 109:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x20001000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x100100001000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4080040000L);
      case 114:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x10000020000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0xc0014000000L);
      case 116:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 2;
         }
         break;
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L);
      case 119:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 2);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 67:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 68:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 69:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0xa90011000000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x40004020000L);
      case 76:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000080000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L);
      case 82:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x208000000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x1080000000L);
      case 84:
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x100000c00000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 100:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0xa90011000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x40004020000L);
      case 108:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000080000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L);
      case 114:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x208000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x1080000000L);
      case 116:
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x100000c00000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 3);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 3);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      case 66:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L);
      case 69:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x100000840000L);
      case 71:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x20001020000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x280000002000L);
      case 84:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x4100080000L);
      case 88:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L);
      case 101:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x100000840000L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x20001020000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x280000002000L);
      case 116:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x4100080000L);
      case 120:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 4);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 4);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 4);
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x40000040000L);
      case 68:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 5;
         }
         break;
      case 69:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x280000080000L);
      case 71:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 5;
         }
         break;
      case 72:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 78:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 5;
         }
         break;
      case 82:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L);
      case 84:
         return jjMoveStringLiteralDfa6_0(active0, 0x10009000000L);
      case 85:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L);
      case 97:
         if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x40000040000L);
      case 100:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 5;
         }
         break;
      case 101:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x280000080000L);
      case 103:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 5;
         }
         break;
      case 104:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 110:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 5;
         }
         break;
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000L);
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x10009000000L);
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 5);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 5);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 5);
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 6;
         }
         break;
      case 67:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000000L);
      case 68:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L);
      case 69:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L);
      case 78:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 6;
         }
         break;
      case 79:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      case 82:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 6;
         }
         break;
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000L);
      case 97:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 6;
         }
         break;
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000000L);
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L);
      case 101:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000L);
      case 110:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 6;
         }
         break;
      case 111:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 6;
         }
         else if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      case 114:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 6;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(0, 6);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 6);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 6);
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 7;
         }
         break;
      case 79:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 7;
         }
         break;
      case 82:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L);
      case 84:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000L);
      case 110:
         if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 7;
         }
         break;
      case 111:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 7;
         }
         break;
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 7);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 7);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 7);
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000000L);
      case 78:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000L);
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000000000L);
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 8);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 8);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 8);
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 9;
         }
         break;
      case 88:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000000L);
      case 97:
         if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 9;
         }
         break;
      case 120:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 9);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 9);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 9);
   }
   switch(curChar)
   {
      case 84:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000000000L);
      case 116:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000000000L);
      default :
         break;
   }
   return jjMoveNfa_0(0, 10);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(0, 10);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(0, 10);
   }
   switch(curChar)
   {
      case 79:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 11;
         }
         break;
      case 111:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 11;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(0, 11);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 26;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAddStates(0, 2);
                  }
                  else if (curChar == 39)
                     jjAddStates(3, 5);
                  else if (curChar == 34)
                     jjCheckNAddStates(6, 9);
                  else if (curChar == 46)
                     jjCheckNAdd(8);
                  else if (curChar == 35)
                  {
                     if (kind > 6)
                        kind = 6;
                     jjCheckNAddStates(10, 12);
                  }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjCheckNAddStates(10, 12);
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 3:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 7:
                  if (curChar == 46)
                     jjCheckNAdd(8);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAdd(8);
                  break;
               case 9:
               case 13:
                  if (curChar == 34)
                     jjCheckNAddStates(6, 9);
                  break;
               case 10:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(6, 9);
                  break;
               case 15:
                  if (curChar == 34 && kind > 52)
                     kind = 52;
                  break;
               case 16:
                  if (curChar == 39)
                     jjAddStates(3, 5);
                  break;
               case 17:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(18);
                  break;
               case 18:
                  if (curChar == 39 && kind > 53)
                     kind = 53;
                  break;
               case 21:
                  if (curChar == 39)
                     jjCheckNAdd(18);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAddStates(0, 2);
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(24);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(25, 7);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 6:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(6);
                  break;
               case 1:
                  if (kind > 6)
                     kind = 6;
                  jjAddStates(10, 12);
                  break;
               case 10:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(6, 9);
                  break;
               case 11:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 12:
                  if ((0x14400010000000L & l) != 0L)
                     jjCheckNAddStates(6, 9);
                  break;
               case 14:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 17:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(18);
                  break;
               case 19:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 20:
                  if ((0x14400010000000L & l) != 0L)
                     jjCheckNAdd(18);
                  break;
               case 22:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 6)
                     kind = 6;
                  jjAddStates(10, 12);
                  break;
               case 10:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(6, 9);
                  break;
               case 17:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 26 - (jjnewStateCnt = startsAt)))
         break;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
static final int[] jjnextStates = {
   24, 25, 7, 17, 19, 22, 10, 11, 14, 15, 1, 2, 4, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\173", "\175", "\133", "\135", "\50", "\51", "\56", "\54", "\72", "\73", "\75", 
"\174\174", "\46\46", "\75\75", "\41\75", "\74", "\76", "\74\75", "\76\75", "\41", "\53", 
"\55", "\52", "\57", "\45", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xfffffffffffff001L, 0x7fffL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[26];
private final int[] jjstateSet = new int[52];
protected char curChar;
/** Constructor. */
public TiraTeimaParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public TiraTeimaParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 26; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
